---
abstract: 'color space conversions and named lookups'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-Color
provides:
  Convert::Color:
    file: lib/Convert/Color.pm
    version: 0.08
  Convert::Color::CMY:
    file: lib/Convert/Color/CMY.pm
    version: 0.08
  Convert::Color::CMYK:
    file: lib/Convert/Color/CMYK.pm
    version: 0.08
  Convert::Color::HSL:
    file: lib/Convert/Color/HSL.pm
    version: 0.08
  Convert::Color::HSV:
    file: lib/Convert/Color/HSV.pm
    version: 0.08
  Convert::Color::RGB:
    file: lib/Convert/Color/RGB.pm
    version: 0.08
  Convert::Color::RGB16:
    file: lib/Convert/Color/RGB16.pm
    version: 0.08
  Convert::Color::RGB8:
    file: lib/Convert/Color/RGB8.pm
    version: 0.08
  Convert::Color::VGA:
    file: lib/Convert/Color/VGA.pm
    version: 0.08
  Convert::Color::X11:
    file: lib/Convert/Color/X11.pm
    version: 0.08
requires:
  List::UtilsBy: 0
  Module::Pluggable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
