---
name: Convert-Color
version: 0.05
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: color space conversions and named lookups
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Pluggable: 0
build_requires:
  Test::More: 0
provides:
  Convert::Color:
    file: lib/Convert/Color.pm
    version: 0.05
  Convert::Color::CMY:
    file: lib/Convert/Color/CMY.pm
    version: 0.05
  Convert::Color::CMYK:
    file: lib/Convert/Color/CMYK.pm
    version: 0.05
  Convert::Color::HSL:
    file: lib/Convert/Color/HSL.pm
    version: 0.05
  Convert::Color::HSV:
    file: lib/Convert/Color/HSV.pm
    version: 0.05
  Convert::Color::RGB:
    file: lib/Convert/Color/RGB.pm
    version: 0.05
  Convert::Color::RGB16:
    file: lib/Convert/Color/RGB16.pm
    version: 0.05
  Convert::Color::RGB8:
    file: lib/Convert/Color/RGB8.pm
    version: 0.05
  Convert::Color::VGA:
    file: lib/Convert/Color/VGA.pm
    version: 0.05
  Convert::Color::X11:
    file: lib/Convert/Color/X11.pm
    version: 0.05
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
